"""add interview round

Revision ID: 35abfa6602fe
Revises: 531cc9ff7fa4
Create Date: 2026-08-31 04:16:16.404919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35abfa6602fe'
down_revision: Union[str, Sequence[str], None] = '531cc9ff7fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('round_number', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_interview_application_round', 'interviews', ['application_id', 'round_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_interview_application_round', 'interviews', type_='unique')
    op.drop_column('interviews', 'round_number')
    # ### end Alembic commands ###
