"""update job table - 1

Revision ID: 36ed79370975
Revises: 8a1e12d67758
Create Date: 2026-08-28 10:11:25.936534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36ed79370975'
down_revision: Union[str, Sequence[str], None] = '8a1e12d67758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('max_experience', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'max_experience')
    # ### end Alembic commands ###
