"""add resume to applications

Revision ID: 905e55bfb475
Revises: 1505498f4c05
Create Date: 2026-08-29 18:47:06.284962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '905e55bfb475'
down_revision: Union[str, Sequence[str], None] = '1505498f4c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('applications', sa.Column('resume_id', sa.Uuid(), nullable=True))

    op.execute(
        """
        UPDATE applications a
        SET resume_id = (
            SELECT r.id
            FROM resumes r
            WHERE r.candidate_id = a.candidate_id
            ORDER BY r.is_default DESC, r.created_at DESC
            LIMIT 1
        )
        WHERE a.resume_id IS NULL
          AND EXISTS (
              SELECT 1
              FROM resumes r
              WHERE r.candidate_id = a.candidate_id
          )
        """
    )

    op.alter_column('applications', 'resume_id', existing_type=sa.Uuid(), nullable=False)
    op.create_foreign_key(
        'fk_applications_resume_id_resumes',
        'applications',
        'resumes',
        ['resume_id'],
        ['id'],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'resume_id')
    # ### end Alembic commands ###
