"""add foreign key in interview table

Revision ID: dc67c80775ce
Revises: 35abfa6602fe
Create Date: 2026-09-06 12:51:11.452987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc67c80775ce'
down_revision: Union[str, Sequence[str], None] = '35abfa6602fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_status_history', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('applications', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.alter_column('interview_feedback', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('interview_feedback', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###w
    op.alter_column('interview_feedback', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('interview_feedback', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('applications', 'rejection_reason')
    op.drop_column('application_status_history', 'updated_at')
    # ### end Alembic commands ###
